/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/inscricao': typeof InscricaoRoute
  '/painel': typeof PainelRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/inscricao': typeof InscricaoRoute
  '/painel': typeof PainelRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/inscricao': typeof InscricaoRoute
  '/painel': typeof PainelRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/checkin' | '/inscricao' | '/painel' | '/politica-de-privacidade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkin' | '/inscricao' | '/painel' | '/politica-de-privacidade'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/inscricao'
    | '/painel'
    | '/politica-de-privacidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  InscricaoRoute: typeof InscricaoRoute
  PainelRoute: typeof PainelRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  InscricaoRoute: InscricaoRoute,
  PainelRoute: PainelRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
